language: generic

sudo: required

services:
  - docker
  -
after_success:
  - docker build -t graphit/f4e-api ./api
  - docker build -t graphit/f4e-client ./client
  - docker build -t graphit/f4e-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push graphit/f4e-api
  - docker push graphit/f4e-client
  - docker push graphit/f4e-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: f4a
  env: F4a-env
  bucket_name: elasticbeanstalk-us-east-2-167510155361
  bucket_path: f4a
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "Encrypted <$AWS_SECRET_KEY>="
