language: generic

sudo: required

services:
  - docker

after_success:
  - docker build -t graphit/f4e-api ./api
  - docker build -t graphit/f4e-client ./client
  - docker build -t graphit/f4e-nginx ./nginx
  - docker build -t graphit/f4e-ssr ./ssr
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push graphit/f4e-api
  - docker push graphit/f4e-client
  - docker push graphit/f4e-nginx
  - docker push graphit/f4e-ssr


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: ffa
  env: Ffa-env
  bucket_name: elasticbeanstalk-us-east-1-242064348210
  bucket_path: ffa
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
