version: '2'
services:
#  web:
#    build: .
#    volumes:
#      - "./app:/src/app"
#    ports:
#      - "3030:3000"
#    links:
#      - "mongo:mongo"
#    environment:
#      - "TEST=${TEST}"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "dbdata:/data/db"
  postgres:
    image: postgres
    restart: always
    volumes:
      - "./app/migrations:/src/app/migrations"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
volumes:
  dbdata:
    driver: local
