#dev
version: '3'
services:
  postgres:
    build:
      dockerfile: Dockerfile.dev
      context: ./postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all"]
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - '9229:9229'
      - '9230:9230'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3001:3000'
  ssr:
    build:
      dockerfile: Dockerfile.dev
      context: ssr
    volumes:
      - /app/node_modules
      - ./ssr:/app
    ports:
      - '4001:4001'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
      - '3053:443'

#prod
#version: '3'
#services:
#  postgres:
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./postgres
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#  api:
#    build:
#      dockerfile: Dockerfile
#      context: ./api
#    volumes:
#      - /app/node_modules
#      - ./api:/app
#    ports:
#      - '9229:9229'
#      - '9230:9230'
#  client:
#    build:
#      dockerfile: Dockerfile
#      context: ./client
#    volumes:
#      - /app/node_modules
#      - ./client:/app
#  nginx:
#    restart: always
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./nginx
#    ports:
#      - '3050:80'
#      - '3053:443'
