FROM node:latest
WORKDIR /app
COPY package.json .
COPY . .
RUN npm i -g typescript ts-node
COPY ./client /app/client
RUN npm i && cp ./client/src/i18n_problem/build_i18n.ts ./client/src/i18n.ts
RUN cd client && npm i
RUN cd client && npm run build
CMD ["npm", "run", "ssr"]
