FROM node:latest
WORKDIR /app
COPY ./package.json .
RUN npm i && npm i --save-dev
RUN npm i -g mocha && npm i -g knex && npm i -g typescript ts-node @types/node
COPY . .
CMD ["npm", "run", "start-dev"]
